version: "3.4"

services:
  dappnode_installer:
    build: build
    privileged: true
    environment:
      - BUILD=false
      - CLEAN=false
      - UNATTENDED=false
    volumes:
      - ./images:/images
